services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cesis-rackschedule:latest
    container_name: cesis-rackschedule
    env_file:
      - .env
    ports:
      - "6000:6000"
    volumes:
      - ./json:/app/json
    restart: unless-stopped
